[env:coreink]
platform = espressif32@^6.5.0
board = m5stack-coreink
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
lib_deps =
    m5stack/M5Unified@^0.2.0
    bblanchon/ArduinoJson@^7.0.0

[env:native]
platform = native
build_flags = -std=c++17 -I test/test_native -I src
build_src_filter = +<modules/daytype.cpp> +<modules/station_nav.cpp> +<modules/timetable_db.cpp>
test_framework = doctest
test_build_src = yes
extra_scripts = pre:scripts/pio_native_clang.py
